greenhouse:
  # Example format:
  # - company: Example Company
  #   board: example

  - company: ExampleCompany
    board: example

lever:
  # Example format:
  # - company: Example Company
  #   board: example

  - company: ExampleCompany
    board: example